### ISSUE TITLE
CRF Parameters

### ISSUE THREAD

**Issue by WangZhenqing-RS** [tianbaochou/NasUnet#1]
您好，我想请问一下，CRF中addPairwiseGaussian函数里的参数是什么意思啊，求指教，谢谢。

**Comment by tianbaochou** [comment]
you cn

> 您好，我想请问一下，CRF中addPairwiseGaussian函数里的参数是什么意思啊，求指教，谢谢。

see https://github.com/lucasb-eyer/pydensecrf/issues/45, but, I do not use this function for now.
