### ISSUE TITLE
requirements are not complete

### ISSUE THREAD

**Issue by ghost** [tianbaochou/NasUnet#10]
@tianbaochou Thank you for your hard work,

The `requirements.txt` file that you provided is not complete, and does not have all the packages required to run NasUnet properly.
Can you upload `environment.yml`, which you can get by running this command:
```
conda env export > environment.yml
```

**Comment by tianbaochou** [comment]
> @tianbaochou Thank you for your hard work,
> 
> The `requirements.txt` file that you provided is not complete, and does not have all the packages required to run NasUnet properly.
> Can you upload `environment.yml`, which you can get by running this command:
> 
> ```
> conda env export > environment.yml
> ```

I have updated the requirements.txt and readme.md file. All of the necessary packages are listed here.

**Comment by ghost** [comment]
@tianbaochou the 'requirements.txt' that you uploaded still have conflicts, I suggest that you create it using:
```
pip freeze > requirements.txt
```
Meanwhile, I uploaded `environment.yml` to install using [conda](https://www.anaconda.com/distribution/).
Please [test before pulling](https://github.com/tianbaochou/NasUnet/pull/13), using:
```
wget https://raw.githubusercontent.com/deepseek/NasUnet/master/environment.yml
conda env create -f environment.yml
conda activate nasunet
```

**Comment by tianbaochou** [comment]
> @tianbaochou the 'requirements.txt' that you uploaded still have conflicts, I suggest that you create it using:
> 
> ```
> pip freeze > requirements.txt
> ```
> 
> Meanwhile, I uploaded `environment.yml` to install using [conda](https://www.anaconda.com/distribution/).
> Please [test before pulling](https://github.com/tianbaochou/NasUnet/pull/13), using:
> 
> ```
> wget https://raw.githubusercontent.com/deepseek/NasUnet/master/environment.yml
> conda env create -f environment.yml
> conda activate nasunet
> ```

I use the cuda9.2 in docker. here is my  environment.yml
 ```
adabound==0.0.5
asn1crypto==0.24.0
certifi==2018.4.16
cffi==1.11.5
chardet==3.0.4
conda==4.5.1
cryptography==2.2.2
cycler==0.10.0
decorator==4.4.0
graphviz==0.10.1
idna==2.6
imageio==2.5.0
kiwisolver==1.1.0
matplotlib==3.0.3
networkx==2.3
numpy==1.16.3
opencv-python==4.1.0.25
Pillow==6.0.0
protobuf==3.7.1
pycosat==0.6.3
pycparser==2.18
pydicom==1.2.2
pyOpenSSL==17.5.0
pyparsing==2.4.0
PySocks==1.6.8
python-dateutil==2.8.0
PyWavelets==1.0.3
PyYAML==5.1
requests==2.18.4
ruamel-yaml==0.15.35
scikit-image==0.15.0
scipy==1.2.1
SimpleITK==1.2.0
six==1.11.0
tensorboardX==1.6
torch==1.1.0
torchvision==0.2.2.post3
tqdm==4.31.1
urllib3==1.22
```

I have test my requirements.txt in a original minianaconda environment. everything is ok.
However, the `requests` package is not included in your environment.yml.
Anyway. thanks you for support my work.
