### ISSUE TITLE
NameError: name 'CitySegmentation' is not defined

### ISSUE THREAD

**Issue by ghost** [tianbaochou/NasUnet#14]
When trying to train using [pascal voc2012](http://host.robots.ox.ac.uk/pascal/VOC/voc2012/#devkit), an error message appear:
```
(nasunet) home@home-lnx:~/Desktop/programs/NasUnet/experiment$ python train.py --config ../configs/nas_unet/nas_unet_voc.yml
Traceback (most recent call last):
  File "train.py", line 14, in <module>
    from util.datasets import get_dataset
  File "../util/datasets/__init__.py", line 21, in <module>
    'citys': CitySegmentation,
NameError: name 'CitySegmentation' is not defined
```

**Comment by tianbaochou** [comment]
> When trying to train using [pascal voc2012](http://host.robots.ox.ac.uk/pascal/VOC/voc2012/#devkit), an error message appear:
> 
> ```
> (nasunet) home@home-lnx:~/Desktop/programs/NasUnet/experiment$ python train.py --config ../configs/nas_unet/nas_unet_voc.yml
> Traceback (most recent call last):
>   File "train.py", line 14, in <module>
>     from util.datasets import get_dataset
>   File "../util/datasets/__init__.py", line 21, in <module>
>     'citys': CitySegmentation,
> NameError: name 'CitySegmentation' is not defined
> ```

the tag v0.01 is a much stable version now.

**Comment by ghost** [comment]
Thanks for solving it!
