### ISSUE TITLE
search_cell.py results in pixACC 0.67 & mIoU 0.03 & loss is constant

### ISSUE THREAD

**Issue by ghost** [tianbaochou/NasUnet#15]
@tianbaochou Thank you for your hard work.
I ran `python search_cell.py` for **18 hours**, and used only **300 images** from the voc 2012 dataset, the results were mostly **pixACC 0.67 & mIoU 0.03**

Why is the mIoU very low, pixACC not improving and loss is constant?

The search folder is attached.
[search-20190516-163658.zip](https://github.com/tianbaochou/NasUnet/files/3190881/search-20190516-163658.zip)

![tensorboard](https://user-images.githubusercontent.com/49877135/57919578-bd269180-78a1-11e9-806e-c86cc762ee2f.jpg)

**Comment by tianbaochou** [comment]
> @tianbaochou Thank you for your hard work.
> I ran `python search_cell.py` for **18 hours**, and used only **300 images** from the voc 2012 dataset, the results were mostly **pixACC 0.67 & mIoU 0.03**
> 
> Why is the mIoU very low, pixACC not improving and loss is constant?
> 
> The search folder is attached.
> [search-20190516-163658.zip](https://github.com/tianbaochou/NasUnet/files/3190881/search-20190516-163658.zip)
> 
> ![tensorboard](https://user-images.githubusercontent.com/49877135/57919578-bd269180-78a1-11e9-806e-c86cc762ee2f.jpg)

Hi,  the images you trained is too small, which are natural images. Since we train the architecture from scratch. the model parameters is not sufficient trained. So, both the pixAcc and mIOU are small.
