### ISSUE TITLE
Search for a new neural architecture using my own dataset

### ISSUE THREAD

**Issue by ghost** [tianbaochou/NasUnet#16]
@tianbaochou 

You have [stated before](https://github.com/tianbaochou/NasUnet/issues/11) that `train.py` uses architectures that you already searched by yourself, which you have placed in [geno_searched.py](https://github.com/tianbaochou/NasUnet/blob/master/models/geno_searched.py)

My question is:
How can I search for a new neural architecture using my own dataset.
I have attached a sample of the dataset below.

[sample.zip](https://github.com/tianbaochou/NasUnet/files/3191972/sample.zip)

**Comment by tianbaochou** [comment]
> @tianbaochou
> 
> You have [stated before](https://github.com/tianbaochou/NasUnet/issues/11) that `train.py` uses architectures that you already searched by yourself, which you have placed in [geno_searched.py](https://github.com/tianbaochou/NasUnet/blob/master/models/geno_searched.py)
> 
> My question is:
> How can I search for a new neural architecture using my own dataset.
> I have attached a sample of the dataset below.
> 
> [sample.zip](https://github.com/tianbaochou/NasUnet/files/3191972/sample.zip)

The README file have show you how to custom your dataset.
The most important thing you need do is locate the image root path. and imitate the dataset class I have overload from torch Dataset.
