### ISSUE TITLE
Searching Space Problem

### ISSUE THREAD

**Issue by JiYuanFeng** [tianbaochou/NasUnet#18]
Thank you for your nice work, I read your paper and the corresponding code, I found that your work involves the cell parameters (alpha) searching which consisted of 3 kinds of cells, however, the stacking  order of these cells is manual design?

**Comment by tianbaochou** [comment]
The manual stacking order we used base on U-Like architecture, such as U-Net. We call backbone. However, you can search backbone by adding it during search like Auto-DeepLab

**Comment by JiYuanFeng** [comment]
Additionally, I found you also use the ProxylessNas search strategy, in this way, you directly search the cells on the target dataset (i.e., the medical image dataset), I am curious about its the performance because typically the medical datasets have limited samples, which easily lead to the overfitting problem.

**Comment by tianbaochou** [comment]
yeah

> Additionally, I found you also use the ProxylessNas search strategy, in this way, you directly search the cells on the target dataset (i.e., the medical image dataset), I am curious about its the performance because typically the medical datasets have limited samples, which easily lead to the overfitting problem.

In fact, we have not do much work on ProxylessNAS, the main reason is the authors not yet release his code.  We provide one of a idea to search on Image Segmentation base on some popular backbone. Recently, much work have drived into the fair of trained operations[(1)](https://arxiv.org/abs/1904.00420) and attempt to use some simple tricks to keep such fairness[(2)](https://arxiv.org/abs/1907.01845). In a word, Sharing weights with a Supernet may be not good for comparing each children network in fair.  In my opinions, there is an urgent need to find a relatively reliable theoretical (Consensus) support Weight-Sharing, or any other accelerate searching tricks when facing a much complicate search space.
