### ISSUE TITLE
How do you do testing?

### ISSUE THREAD

**Issue by jiangmenghua** [tianbaochou/NasUnet#20]
I have tried to run the
`python train.py --config ../configs/nas_unet/nas_unet_voc.yml`

I tried running it for a short 100 epochs and 2 gpus, the running was ok. It generates some files in the logs folder. I have the following queries:

1. There was nothing in the saved_val_images folder. Is it supposed to be so?
2. I have gotten the checkpint.pth.tar and model_best.pth.tar. I can load the weights. How do I test them? Just run it again like the training?

Thank you.
-------------------------------------------------------------------------
edit #1: 2019-09-11
I am also having difficulty finding the trained structure, I mean where do I look for the architecture after searching? I could load the saved model parameters into a model rebuilt from the initial training configurations.

**Comment by tianbaochou** [comment]
> I have tried to run the
> `python train.py --config ../configs/nas_unet/nas_unet_voc.yml`
> 
> I tried running it for a short 100 epochs and 2 gpus, the running was ok. It generates some files in the logs folder. I have the following queries:
> 
> 1. There was nothing in the saved_val_images folder. Is it supposed to be so?
> 2. I have gotten the checkpint.pth.tar and model_best.pth.tar. I can load the weights. How do I test them? Just run it again like the training?
> 
> ## Thank you.
> edit #1: 2019-09-11
> I am also having difficulty finding the trained structure, I mean where do I look for the architecture after searching? I could load the saved model parameters into a model rebuilt from the initial training configurations.

1. You can found  the architecture in log file.  
2. I comment the save_val_images functions, however support tensorboardX.
