### ISSUE TITLE
关于experiment/test.py中的valid和test数据集问题

### ISSUE THREAD

**Issue by Yanxingang** [tianbaochou/NasUnet#25]
test.py是为了测试最后得到网络的mIOU的
其中，trainset、valset、testset都是相同的数据集目录，也就是data都是相同的，那么后面用train的数据集再作为test的数据集，理论上不是有错误吗？
还望解答！

**Comment by tianbaochou** [comment]
> test.py是为了测试最后得到网络的mIOU的
> 其中，trainset、valset、testset都是相同的数据集目录，也就是data都是相同的，那么后面用train的数据集再作为test的数据集，理论上不是有错误吗？
> 还望解答！

你好，目前testset仅仅只是编码的时候开放的，并没有实际使用。因为NAS-Unet在对比FC-Densenet, Unet等网络结构Performance时用的是valset。
trainset, valset, testset目录相同，是因为train和val的数据是Dataloader自动split的(由于很多数据没有分train/val)。

很多医学图像比赛都是3D数据，所以一般需要用户自己根据需要在进行test的时候做一些处理，以便更好的合成3D预测数据。
