### ISSUE TITLE
Actually searching for a neural architecture

### ISSUE THREAD

**Issue by ghost** [tianbaochou/NasUnet#28]
@tianbaochou 
Thanks for your hard work,

1- The Readme doesn't show how to use `search_cell.py` in-order to search for a new architecture
2- How many images are enough to search or a new architecture?
3-  Does NasUnet search using **cropped** of the ground-truth images, or downscaled images?

**Comment by tianbaochou** [comment]
> @tianbaochou
> Thanks for your hard work,
> 
> 1- The Readme doesn't show how to use `search_cell.py` in-order to search for a new architecture
> 2- How many images are enough to search or a new architecture?
> 3- Does NasUnet search using **cropped** of the ground-truth images, or downscaled images?

Sorry for the late response
1.  DARTS and it's variants may find a new architecture when you run different times on the same parameter settings.
2.  It depands on #classes of dataset
3. Yes
