### ISSUE TITLE
is the NasUnet can support GPU-CLUSTER?or do you plan to do so?

### ISSUE THREAD

**Issue by berisfu** [tianbaochou/NasUnet#3]

**Comment by tianbaochou** [comment]
You are right, I will extend this work to support GPU-CLUSTER later, which called **CNASV**.

**Comment by tianbaochou** [comment]
close it

**Comment by Minotaur-CN** [comment]
Hi. I did not find the CNASV in your repo?
Can u reopen that repo? Thanks!
