### ISSUE TITLE
when i run python search_cell.py for Ultrasound_nerve dataset, error occurs: ['searcing']['alpha_begin'] and ['searching']['max_patience'] are not found. 

### ISSUE THREAD

**Issue by berisfu** [tianbaochou/NasUnet#4]

**Comment by tianbaochou** [comment]
I search the cell architecture on PASCAL VOC dataset, so you can look at configs/nas_unet/nas_unet_voc.yml. 
 Default:    
```yaml
alpha_begin: 10  max_patience: 40
```

**Comment by berisfu** [comment]
> I search the cell architecture on PASCAL VOC dataset, so you can look at configs/nas_unet/nas_unet_voc.yml.
> Default:
> 
> ```yaml
> alpha_begin: 10  max_patience: 40
> ```


great job.
so can you explain the items in config file?

**Comment by tianbaochou** [comment]
> > I search the cell architecture on PASCAL VOC dataset, so you can look at configs/nas_unet/nas_unet_voc.yml.
> > Default:
> > ```yaml
> > alpha_begin: 10  max_patience: 40
> > ```
> 
> great job.
> so can you explain the items in config file?

`alpha_begin` is a threshold indicates the architecture parameters not updated until the epoch greater than `alpha_begin`.  `max_patience` means when the architecture encoding not changed threshold is for `max_patience` epoch. The details can be found from our paper.
