### ISSUE TITLE
if the shape of my images is neither RGB(in_channel=3) nor monochrome(in_channel=1).its shape is [110,110,7].can the NASUnet support this case?

### ISSUE THREAD

**Issue by berisfu** [tianbaochou/NasUnet#5]
at the same time,the output shape is [110,110,1]

**Comment by tianbaochou** [comment]
> at the same time,the output shape is [110,110,1]

you can custom your personal  pytorch dataset loader. see [here](https://github.com/tianbaochou/NasUnet/blob/bac2dc485249e37befdfab9241c275aabf9ed78c/experiment/search_cell.py#L103).

If you want to search on you dataset, you need change the in_channels( which means  the channel of input image)as 7. at [here](https://github.com/tianbaochou/NasUnet/blob/bac2dc485249e37befdfab9241c275aabf9ed78c/experiment/search_cell.py#L103). Same as Training.

the output shape is one-hot encoding. For example, if you have `C` classes, the output size is [N, C, W, H].  You can output the result use `torch.argmax`. see [here](https://github.com/tianbaochou/NasUnet/blob/bac2dc485249e37befdfab9241c275aabf9ed78c/experiment/test.py#L196)
