### ISSUE TITLE
whether your code is just for IN_CHANNELS equal 1?

### ISSUE THREAD

**Issue by berisfu** [tianbaochou/NasUnet#9]
when i try to run the code for camvid, the following error appears.
whether the target must be 3 dimension which means the channel of target must be 1.

I also find that your paper figure it out the nas-unet can get better performance on chaos,ultrasound_nerve,promise12 ,which are have only one channel.

 File "C:\Users\f00335061\AppData\Local\Continuum\anaconda3\lib\site-packages\torch\nn\functional.py", line 1792, in nll_loss
    ret = torch._C._nn.nll_loss2d(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
RuntimeError: invalid argument 3: only batches of spatial targets supported (3D tensors) but got targets of dimension: 4 at c:\a\w\1\s\windows\pytorch\aten\src\thnn\generic/SpatialClassNLLCriterion.c:59

**Comment by tianbaochou** [comment]
> when i try to run the code for camvid, the following error appears.
> whether the target must be 3 dimension which means the channel of target must be 1.
> 
> I also find that your paper figure it out the nas-unet can get better performance on chaos,ultrasound_nerve,promise12 ,which are have only one channel.
> 
> File "C:\Users\f00335061\AppData\Local\Continuum\anaconda3\lib\site-packages\torch\nn\functional.py", line 1792, in nll_loss
> ret = torch._C._nn.nll_loss2d(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
> RuntimeError: invalid argument 3: only batches of spatial targets supported (3D tensors) but got targets of dimension: 4 at c:\a\w\1\s\windows\pytorch\aten\src\thnn\generic/SpatialClassNLLCriterion.c:59

I have update this.

**Comment by berisfu** [comment]
The error still exists for the tag 0.0.1

RuntimeError: invalid argument 3: only batches of spatial targets supported (3D tensors) but got targets of dimension: 4 at c:\a\w\1\s\windows\pytorch\aten\src\thnn\generic/SpatialClassNLLCriterion.c:59

**Comment by berisfu** [comment]
> The error still exists for the tag 0.0.1
> 
> RuntimeError: invalid argument 3: only batches of spatial targets supported (3D tensors) but got targets of dimension: 4 at c:\a\w\1\s\windows\pytorch\aten\src\thnn\generic/SpatialClassNLLCriterion.c:59

also run the code for camvid, the same error still be here.

**Comment by tianbaochou** [comment]
> > The error still exists for the tag 0.0.1
> > RuntimeError: invalid argument 3: only batches of spatial targets supported (3D tensors) but got targets of dimension: 4 at c:\a\w\1\s\windows\pytorch\aten\src\thnn\generic/SpatialClassNLLCriterion.c:59
> 
> also run the code for camvid, the same error still be here.

It was weird, I have tested all of the code from scratch in a new docker environment on ubuntu16.04 and win10. All of them work well.  I suggest you to check on code

**Comment by berisfu** [comment]
i run the python search_cell.py under Win10 and ubuntu. The following error appears without any modification on your code:
RuntimeError: 1only batches of spatial targets supported (non-empty 3D tensors) but got targets of size: : [6, 256, 256, 3]

I print the size of img and target tensor,img shape(3,256,256) while target shape (256,256,3).
so I must change target = target.transpose(0,2).transpose(1,2) to change tensor to (3,256,256).
After that,another error occurs:
RuntimeError: invalid argument 3: only batches of spatial targets supported (3D tensors) but got targets of dimension: 4 at c:\a\w\1\s\windows\pytorch\aten\src\thnn\generic/SpatialClassNLLCriterion.c:59

so whether I should change the target shape into （256,256）instead of （3,256,256）？

**Comment by berisfu** [comment]
I find the reason.
my camvid mask file have a name with suffix “_L.png”, just like 0001TP_008730_L.png. The mask files are RGB,which means it has more than one channel. The camvid mask file you are using are monochrome.

So，unfortunately，the code is not suit for cityscapes，camvid with RGB mask.
